spring:
  main:
    allow-circular-references: true
  application:
    name: insurance2206823682
  datasource:
    url: jdbc:postgresql://localhost:15001/tk-apap-50
    username: tk-apap-50
    password: tk-apap-50
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 8081
insurance2206823682:
  app:
    jwtSecret: "hPjbJwZKskRmCnzroyAZfglqSKexYmxKeYPvSvJ"
    jwtExpirationMs: 86400000
