spring:
  application:
    name: insurance2206823682
  datasource:
    url: jdbc:postgresql://localhost:15001/insurance2206823682
    username: postgres
    password: secret99
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
